package com.clinica_medica.enums;

public enum Especialidades {
    ODONTOLOGIA, OTORRINOLARINGOLOGISTA, CARDIOLOGISTA, ENDOCRINOLOGISTA, NUTRICIONISTA, OFTALMOLOGISTA, FISIOTERAPIA, CIRURGIÃO,
    ONCOLOGISTA, NEUROLOGISTA;
}
